export let GROUP_SAVE_FAIL = 'GROUP_SAVE_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GROUP_SAVE = 'GROUP_SAVE';
export const GROUP_SAVE_SUCCESS = 'GROUP_SAVE_SUCCESS';
export const GROUP_GET_ALL = 'GROUP_ALL_GET';
export const GROUP_GET_ALL_SUCCESS = 'GROUP_GET_ALL_SUCCESS';
export const GROUP_GET_ALL_FAILURE = 'GROUP_GET_ALL_FAILURE';


/*actions for create card*/
export const CARD_CREATE_START = 'CARD_CREATE_START';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILURE = 'CARD_CREATE_FAILURE';

/*actions for update card*/
export const CARD_UPDATE_START = 'CARD_UPDATE_START';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS';
export const CARD_UPDATE_FAILURE = 'CARD_UPDATE_FAILURE';

/*read one card cards*/
export const CARD_READ_START = 'CARD_READ_START';
export const CARD_READ_SUCCESS = 'CARD_READ_SUCCESS';
export const CARD_READ_FAILURE = 'CARD_READ_FAILURE';

/*get all cards for a group*/
export const GROUP_CARD_READ_START = 'GROUP_CARD_READ_START';
export const GROUP_CARD_READ_SUCCESS = 'GROUP_CARD_READ_SUCCESS';
export const GROUP_CARD_READ_FAILURE = 'GROUP_CARD_READ_FAILURE';


/*get useradmin view for a group*/
export const GROUP_ADMIN_VIEW_READ_START = 'GROUP_ADMIN_VIEW_READ_START';
export const GROUP_ADMIN_VIEW_READ_SUCCESS = 'GROUP_ADMIN_VIEW_READ_SUCCESS';
export const GROUP_ADMIN_VIEW_READ_FAILURE = 'GROUP_ADMIN_VIEW_READ_FAILURE';

/*toggle useradmin*/
export const GROUP_ADMIN_TOGGLE_START = 'GROUP_ADMIN_TOGGLE_START';
export const GROUP_ADMIN_TOGGLE_SUCCESS = 'GROUP_ADMIN_TOGGLE_SUCCESS';
export const GROUP_ADMIN_TOGGLE_FAILURE = 'GROUP_ADMIN_TOGGLE_FAILURE';

/*create standalone tiny url*/
export const CREATE_TINY_URL_START = 'CREATE_TINY_URL_START';
export const CREATE_TINY_URL_SUCCESS = 'CREATE_TINY_URL_SUCCESS';
export const CREATE_TINY_URL_FAILURE = 'CREATE_TINY_URL_FAILURE';

export const HIDE_TINY_URL_MODAL = 'HIDE_TINY_URL_MODAL';

/*show all tiny urls of the user*/
export const SHOW_MY_TINY_URLS_START = 'SHOW_MY_TINY_URLS';
export const SHOW_MY_TINY_URLS_SUCCESS = 'SHOW_MY_TINY_URLS_SUCCESS';
export const SHOW_MY_TINY_URLS_FAILURE = 'SHOW_MY_TINY_URLS_FAILURE';




