export let GROUP_SAVE_FAIL = 'GROUP_SAVE_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GROUP_SAVE = 'GROUP_SAVE';
export const GROUP_SAVE_SUCCESS = 'GROUP_SAVE_SUCCESS';
export const GROUP_GET_ALL = 'GROUP_ALL_GET';
export const GROUP_GET_ALL_SUCCESS = 'GROUP_GET_ALL_SUCCESS';
export const GROUP_GET_ALL_FAILURE = 'GROUP_GET_ALL_FAILURE';


/*actions for create card*/
export const CARD_CREATE_START = 'CARD_CREATE_START';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILURE = 'CARD_CREATE_FAILURE';

/*actions for update card*/
export const CARD_UPDATE_START = 'CARD_UPDATE_START';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS';
export const CARD_UPDATE_FAILURE = 'CARD_UPDATE_FAILURE';

/*read one card cards*/
export const CARD_READ_START = 'CARD_READ_START';
export const CARD_READ_SUCCESS = 'CARD_READ_SUCCESS';
export const CARD_READ_FAILURE = 'CARD_READ_FAILURE';

/*get all cards for a group*/
export const GROUP_CARD_READ_START = 'GROUP_CARD_READ_START';
export const GROUP_CARD_READ_SUCCESS = 'GROUP_CARD_READ_SUCCESS';
export const GROUP_CARD_READ_FAILURE = 'GROUP_CARD_READ_FAILURE';